name: Add team label

on:
  pull_request:
    types:
      - opened

jobs:
  add-team-label:
    uses: metamask/metamask-planning/.github/workflows/add-team-label.yml@feat/make-add-team-label-a-reusable-workflow
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.RELEASE_LABEL_TOKEN }}
