name: Add team label

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  add-team-label:
    uses: metamask/github-tools/.github/workflows/add-team-label.yml@add-team-label
    permissions:
       pull-requests: write
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.RELEASE_LABEL_TOKEN }}
