name: 'Run Benchmarks'

on: workflow_call

jobs:
  benchmark:
    name: Benchmark
    # runs-on: ubuntu-latest
    # runs-on: [self-hosted, Linux, X64]
    runs-on: gha-mm-scale-set-ubuntu-22.04-amd64-med
    container:
      image: cimg/node:20.18-browsers
      # options: --user root
    steps:
      - name: Setup environment
        uses: MetaMask/metamask-extension/.github/actions/setup-environment@self-hosted-temp
        with:
          should-cache-restore: true

      # - name: Debugging with tmate
      #   uses: ./.github/actions/actions-tmate

      # - run: |
      #     curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
      #     source ~/.nvm/nvm.sh
      #     nvm install 20
      #     node -v # should print `v20.18.1`.
      #     apt-get update
      #     apt-get install gh

      # - run: corepack enable
      #   shell: bash

      # - name: Set up Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version-file: .nvmrc
      #     cache: yarn
      #     cache-dependency-path: yarn.lock

      # - name: Install dependencies
      #   run: yarn
      #   shell: bash

      # - run: yarn build:test
      - run: yarn webpack --test

      - name: Install prereqs
        run: |
          # apt-get update
          # apt-get install -y xvfb
          # apt-get -y install xorg xvfb gtk2-engines-pixbuf
          # apt-get -y install dbus-x11 xfonts-base xfonts-100dpi xfonts-75dpi xfonts-cyrillic xfonts-scalable
          Xvfb -ac :99 -screen 0 1280x1024x16 &
          # export DISPLAY=:99

      - name: Run the benchmark
        run: yarn benchmark:chrome --out test-artifacts/chrome/benchmark/pageload.json --retries 2

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: pageload
          path: test-artifacts/chrome/benchmark/pageload.json
          retention-days: 5
# user-actions-benchmark:
#   name: User Actions Benchmark
