name: CI

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  merge_group:

jobs:
  run-tests:
    name: Run tests
    uses: ./.github/workflows/run-tests.yml
