name: Run unit tests

on:
  pull_request:
    types: [opened,reopened,synchronize]

jobs:
  test-unit-jest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - run: corepack enable

      - name: Install dependencies
        run: yarn --immutable

      - name: test:coverage:jest
        run: yarn test:coverage:jest

  test-unit-jest-development:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - run: corepack enable

      - name: Install dependencies
        run: yarn --immutable

      - name: test:coverage:jest:dev
        run: yarn test:coverage:jest:dev
