name: Run unit tests

on:
  pull_request:
    types: [opened,reopened,synchronize]

jobs:
  test-unit-jest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: test:coverage:jest:dev
        run: yarn test:coverage:jest:dev

      - name: test:coverage:jest
        run: yarn test:coverage:jest

      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
