# This GitHub action will checkout and scan third party code.
# Please ensure that any changes to this action do not perform
# actions that may result in code from that branch being executed
# such as installing dependencies or running build scripts.

name: SonarCloud

on:
  workflow_run:
    workflows:
      - Run tests
    types:
      - completed

jobs:
  sonarcloud:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.workflow_run.head_repository.full_name }} # Use the repository that triggered the workflow
          ref: ${{ github.event.workflow_run.head_branch }} # Use the branch that triggered the workflow
          fetch-depth: 0  # Shallow clones should be disabled for better relevancy of analysis

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: lcov.info
          path: coverage

      - name: SonarCloud Scan
        # This is SonarSource/sonarcloud-github-action@v2.0.0
        uses: SonarSource/sonarcloud-github-action@4b4d7634dab97dcee0b75763a54a6dc92a9e6bc1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
